// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
