// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.org.example.proto

package org.example.proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
