// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.org.example.proto

package org.example.proto;

public interface HelloResposeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.HelloRespose)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
