// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.org.example.proto

package org.example.proto;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HelloRespose_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HelloRespose_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentDo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentDo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentDoList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentDoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.org.example.proto\022\005proto\"\034\n\014HelloRequest\022\014" +
      "\n\004name\030\001 \001(\t\"\032\n\014HelloRespose\022\n\n\002id\030\001 \001(\005" +
      "\"\027\n\tStudentId\022\n\n\002id\030\001 \001(\005\"&\n\tStudentDo\022\014" +
      "\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"2\n\rStudentDoLi" +
      "st\022!\n\007student\030\001 \003(\0132\020.org.example.proto.StudentDo2\373\001" +
      "\n\016StudentService\0229\n\013GetIdByName\022\023.org.example.proto." +
      "HelloRequest\032\023.org.example.proto.HelloRespose\"\000\0229\n\017G" +
      "etStudentsById\022\020.org.example.proto.StudentId\032\020.org.example.proto" +
      ".StudentDo\"\0000\001\022>\n\020GetStudentsByIds\022\020.pro" +
      "to.StudentId\032\024.org.example.proto.StudentDoList\"\000(\001\0223" +
      "\n\007BioTalk\022\020.org.example.proto.StudentId\032\020.org.example.proto.Stud" +
      "entDo\"\000(\0010\001B\022\n\005protoB\007StudentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_proto_HelloRespose_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_HelloRespose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HelloRespose_descriptor,
        new String[] { "Id", });
    internal_static_proto_StudentId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_StudentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentId_descriptor,
        new String[] { "Id", });
    internal_static_proto_StudentDo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_StudentDo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentDo_descriptor,
        new String[] { "Name", "Age", });
    internal_static_proto_StudentDoList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_StudentDoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentDoList_descriptor,
        new String[] { "Student", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
