// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.org.example.proto

package org.example.proto;

public interface StudentDoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.StudentDoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.proto.StudentDo student = 1;</code>
   */
  java.util.List<StudentDo>
      getStudentList();
  /**
   * <code>repeated .org.example.proto.StudentDo student = 1;</code>
   */
  StudentDo getStudent(int index);
  /**
   * <code>repeated .org.example.proto.StudentDo student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .org.example.proto.StudentDo student = 1;</code>
   */
  java.util.List<? extends StudentDoOrBuilder>
      getStudentOrBuilderList();
  /**
   * <code>repeated .org.example.proto.StudentDo student = 1;</code>
   */
  StudentDoOrBuilder getStudentOrBuilder(
          int index);
}
